Tracker:
  _target_: helicopter.vision.tracking.Tracker
  _partial_: True
  point_handler:
    _target_: helicopter.vision.tracking.TrackingPointHandler
    detector:
      _target_: helicopter.vision.point_detection.YOLOPointDetector
      marker_tolerance: 0.01
      distance_threshold: 4.0
      marker_std_dev: 0.01
      margin: 2
      model:
        _target_: helicopter.vision.point_detection.HelicopterYOLO
        model:
          _target_: ultralytics.YOLO
          model: '/home/ray/yolo_models/helicopter/track_20260401_3/weights/best.engine'
          task: "detect"
        preprocessor:
          _target_:  helicopter.vision.point_detection.GPUImagePreprocessor
          imgsz:
            - 720
            - 1280
        imgsz:
          - 720
          - 1280
        conf: 0.15
    matcher:
      _target_: helicopter.vision.tracking.TrianglePointMatcher
      n: 10
      reference_points_path: 'assets/point_clouds/green_syma.npy'
    max_icp_iters: 10
  camera:
    _target_: helicopter.vision.D435i
    enable_motion: true
    enable_rgb: true
    video_rate: 30
    video_resolution:
      - 720
      - 1280
    projector_power: 0.0
    autoexpose: false
    exposure_time: 3000
    autoexpose_rgb: false
    exposure_time_rgb: 500
    depth_preset: 3
    ema_accel: 1.0
  ukf_factory:
    _target_: helicopter.vision.UKFFactory
    dt: 0.005
    N: 15
    alpha: 0.1
    beta: 2.0
    kappa: -12.0
    q_std_devs:
      gyro: 1.5
      pos: 1.0e-6
      vel: 7.5e-2
      bias_acc: 1.0e-7
      bias_gyro: 1.0e-7
    s_std_devs:
      d_theta: 0.2
      dp: 1.0e-4
      dv: 1.0e-3
      dba: 1.0e-5
      dbg: 1.0e-5
    r_std_devs:
      dp_x: 1.0e-2
      dp_y: 1.0e-2
      dp_z: 1.0e-2
  simulation_fps: 250.
