name: helicopter
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cmake
  - eigen
  - pybind11
  - scikit-build-core
  - pip
  - jax
  - numpy
  - scipy
  - ultralytics
  - tqdm
  - opencv-python-headless
  - numpy-quaternion
  - pandas
  - matplotlib